In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/food-prices-in-turkey/train.csv
/kaggle/input/food-prices-in-turkey/test.csv

In [1]:
train_path = '../input/food-prices-in-turkey/train.csv'
test_path= '../input/food-prices-in-turkey/test.csv'

In [4]:
df = pd.read_csv(train_path)

In [5]:
df

,Place,ProductId,ProductName,UmId,UmName,Month,Year,Price
0,National Average,52,Rice - Retail,5,KG,5,2013,4.4920
1,National Average,52,Rice - Retail,5,KG,6,2013,4.5786
2,National Average,52,Rice - Retail,5,KG,11,2013,4.7865
3,National Average,52,Rice - Retail,5,KG,12,2013,5.1337
4,National Average,52,Rice - Retail,5,KG,1,2014,5.5099
...,...,...,...,...,...,...,...,...
7376,Izmir,502,Cocoa (powder) - Retail,5,KG,8,2019,47.9040
7377,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,49.1176
7378,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50.8347
7379,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,51.7985
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,51.6071

In [6]:
df.Place.unique()

array(['National Average', 'Ankara', 'Istanbul', 'Izmir'], dtype=object)

In [8]:
df.Place = df.Place.replace('National Average',0)
df.Place = df.Place.replace('Ankara',1)
df.Place = df.Place.replace('Istanbul',2)
df.Place = df.Place.replace('Izmir',3)

In [9]:
df.Place.unique()

array([0, 1, 2, 3])

In [10]:
df = df.drop(['ProductName', 'UmName','Month'], axis=1)

In [11]:
def z_score_normalize(X):
    m = X.shape[0]
    n = 1
    for i in range(n):
        X = (X - X.mean(axis=0))/X.std(axis=0)
    return X

In [12]:
Y = df['Price']
X = df.drop(['Price'], axis=1)

In [13]:
Y = z_score_normalize(Y)

In [14]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

In [15]:
model= LinearRegression()

In [16]:
model.fit(X, Y)

LinearRegression()

In [17]:
test_data = pd.read_csv(test_path)

In [18]:
test_data = test_data.drop(['ProductName', 'UmName','Month'], axis=1)

In [20]:
test_data.Place = df.Place.replace('National Average',0)
test_data.Place = df.Place.replace('Ankara',1)
test_data.Place = df.Place.replace('Istanbul',2)
test_data.Place = df.Place.replace('Izmir',3)

In [21]:
y = test_data['Price']
x = test_data.drop(['Price'],axis = 1)

In [22]:
y.describe()

count    868.000000
mean      21.134552
std       28.194908
min        0.760000
25%        5.708250
50%        7.644600
75%       32.964000
max      166.904600
Name: Price, dtype: float64

In [23]:
y = z_score_normalize(y)

In [24]:
x

     Place  ProductId  UmId  Year
0        0         52     5  2021
1        0         52     5  2021
2        0         52     5  2021
3        0         52     5  2021
4        0         52     5  2021
..     ...        ...   ...   ...
863      0        502     5  2021
864      0        502     5  2021
865      0        502     5  2021
866      0        502     5  2021
867      0        502     5  2021

[868 rows x 4 columns]

In [25]:
preds = model.predict(x)

In [26]:
mean_absolute_error(y, preds)

0.7799578317655936